name: build

on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_REGISTRY_INDEX: index.docker.io/aemdesign
      ORGANISATION_NAME: aemdesign
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GOOGLE_DRIVEID_AEM: ${{ secrets.GOOGLE_DRIVEID_AEM64 }}
      GOOGLE_DRIVEID_AEM_SP: ${{ secrets.GOOGLE_DRIVEID_AEM648_SP }}
      GOOGLE_DRIVEID_AEM_SP_CFP: ${{ secrets.GOOGLE_DRIVEID_AEM648_SP_CFP }}
      GOOGLE_DRIVEID_AEM_FORMS: ${{ secrets.GOOGLE_DRIVEID_AEM648_FORMS }}
      GOOGLE_DRIVEID_AEM_FORMSPC: ${{ secrets.GOOGLE_DRIVEID_AEM648_FORMSCP }}
      GOOGLE_DRIVEID_AEM_VANITYURL: ${{ secrets.GOOGLE_DRIVEID_AEM_VANITYURL }}
      GOOGLE_DRIVEID_AEM_CONTENTTRANSFER: ${{ secrets.GOOGLE_DRIVEID_SDK_CONTENTTRANSFER_1_3_4 }}
      CREDS_ADOBE: ${{ secrets.CREDS_ADOBE }}
      PACKAGE_PATH: "./packages"
      JAR_PATH: "./jar"
      PYTHON_VERSION: 3.6


    steps:
      - name: Experimental Status
        run: |
          docker version -f '{{.Server.Experimental}}'
      - name: Docker
        run: |
          docker version -f '{{.Server.Experimental}}'
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker version -f '{{.Server.Experimental}}'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
          sudo rm /etc/docker/daemon.json
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@v2
      - name: set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: set envirnment variables
        id: config
        run: |
          echo GET PACKAGES
          export PACKAGE_PATH=$(pwd)/packages
          echo "{PACKAGE_PATH}={PACKAGE_PATH}" >> $GITHUB_ENV
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/github_get_config.sh)
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/download-gdrive.sh)
          echo $PACKAGE_PATH
          echo $JAR_PATH
          if [[ ! -d $PACKAGE_PATH ]]; then mkdir $PACKAGE_PATH; fi
          if [[ ! -d $JAR_PATH ]]; then mkdir $JAR_PATH; fi
          echo PACKAGES CONTENTS $PACKAGE_PATH
          ls -latr $PACKAGE_PATH
          echo DOWNLOAD JAR INTO ${JAR_PATH}
          downloadGDrive "download" "$GOOGLE_DRIVEID_AEM" "$JAR_PATH/aem-quickstart.jar"
          echo DOWNLOAD PACKAGES INTO ${PACKAGE_PATH}
          # ============================================
          # PACKAGE INSTALL
          # ============================================
          export PACKAGE_CKECK_COUNT=6
          # --------------------------------------------
          downloadGDrive "download" "${GOOGLE_DRIVEID_AEM_SP}" "$PACKAGE_PATH/01-aem-service-pkg-6.4.8.zip"
          downloadGDrive "download" "${GOOGLE_DRIVEID_AEM_SP_CFP}" "$PACKAGE_PATH/02-aem-6.4.8-cfp-4.0.zip"
          downloadGDrive "download" "${GOOGLE_DRIVEID_AEM_FORMS}" "$PACKAGE_PATH/03-adobe-aemfd-linux-pkg-5.1.212.zip"
          downloadGDrive "download" "${GOOGLE_DRIVEID_AEM_FORMSCP}" "$PACKAGE_PATH/04-adobe-aemfd-compat-pkg-1.1.18.zip"
          downloadGDrive "download" "${GOOGLE_DRIVEID_AEM_VANITYURL}" "$PACKAGE_PATH/05-vanityurls-components-1.0.6.zip"
          downloadGDrive "download" "${GOOGLE_DRIVEID_AEM_CONTENTTRANSFER}" "$PACKAGE_PATH/06-content-transfer.all-1.3.4.zip"
          #./scripts/download.sh "$PACKAGE_PATH/06-" "-" "-" "https://github.com/adobe/aem-core-wcm-components/releases/download/core.wcm.components.reactor-2.15.2/core.wcm.components.all-2.15.2.zip"
          #./scripts/download.sh "$PACKAGE_PATH/07-" "-" "-" "https://github.com/Adobe-Consulting-Services/com.adobe.acs.bundles.twitter4j/releases/download/com.adobe.acs.bundles.twitter4j-1.0.0/com.adobe.acs.bundles.twitter4j-content-1.0.0.zip"
          #./scripts/download.sh "$PACKAGE_PATH/08-" "-" "-" "https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/download/acs-aem-commons-5.0.4/acs-aem-commons-content-5.0.4.zip"
          #./scripts/download.sh "$PACKAGE_PATH/09-" "-" "-" "https://repo1.maven.org/maven2/biz/netcentric/cq/tools/accesscontroltool/accesscontroltool-package/2.8.0/accesscontroltool-package-2.8.0.zip"
          #./scripts/download.sh "$PACKAGE_PATH/10-" "-" "-" "https://repo1.maven.org/maven2/biz/netcentric/cq/tools/accesscontroltool/accesscontroltool-oakindex-package/2.8.0/accesscontroltool-oakindex-package-2.8.0.zip"
          #./scripts/download.sh "$PACKAGE_PATH/11-" "-" "githublatest:aemdesign-aem-core-deploy" "https://api.github.com/repos/aem-design/aemdesign-aem-core/releases/latest"
          #./scripts/download.sh "$PACKAGE_PATH/12-" "-" "githublatest:aemdesign-aem-support-deploy" "https://api.github.com/repos/aem-design/aemdesign-aem-support/releases/latest"
          #./scripts/download.sh "$PACKAGE_PATH/13-" "-" "githublatest:brightcove_connector" "https://api.github.com/repos/aem-design/Adobe-AEM-Brightcove-Connector/releases/latest"
          # --------------------------------------------
          echo "{PACKAGE_CKECK_COUNT}={PACKAGE_CKECK_COUNT}" >> $GITHUB_ENV
          echo ::set-output name=PACKAGE_CKECK_COUNT::$PACKAGE_CKECK_COUNT
          echo PACKAGE COUNT=$PACKAGE_CKECK_COUNT
          ls -latr $PACKAGE_PATH
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/github_get_version.sh)

      - name: build and test docker image
        run: |
          docker build --pull --squash -t $IMAGE:$GIT_BRANCH .
          (cd test && bash ./run_tests.sh "$IMAGE:$GIT_BRANCH" "$PACKAGE_CKECK_COUNT")
          docker images
        env:
          PACKAGE_CKECK_COUNT: ${{ steps.config.outputs.PACKAGE_CKECK_COUNT }}

      - name: login to docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${DOCKER_REGISTRY} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: push image version
        run: |
          docker push $IMAGE:$GIT_BRANCH
      - name: push latest image on master
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag $IMAGE:$GIT_BRANCH $IMAGE:latest
          docker push $IMAGE:latest

      - name: update registry description with readme on master
        if: github.ref == 'refs/heads/master'
        run: |
          docker run --rm -v $(pwd):/data/ aemdesign/dockerhub-description "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$IMAGE"

      - name: create release ${{ env.GITHUB_TAG }}
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_TAG }}
          release_name: ${{ env.GITHUB_TAG }}
          body: ${{ steps.config.outputs.GIT_RELEASE_NOTES }}
          draft: false
          prerelease: false
